package com.example.model

import androidx.compose.foundation.BorderStroke
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

data class CommonAccountInfo(
    val code: String,
    val name: String,
    val nature: PucNature,
    val description: String,
    val debitDynamic: String,
    val creditDynamic: String,
    val practicalExample: String
)

fun getAccountBorder(code: String, defaultColor: Color): BorderStroke {
    val isCommon = CommonAccountsHelper.commonAccountsList.any { it.code == code }
    return if (isCommon) {
        BorderStroke(1.5.dp, Color(0xFFFFB300)) // Subtle golden amber border for 69 common accounts
    } else {
        BorderStroke(1.dp, defaultColor)
    }
}

object CommonAccountsHelper {
    val commonAccountsList = listOf(
        CommonAccountInfo("110505", "Caja general", PucNature.DEBITO,
            "Efectivo disponible en la caja principal de la empresa.",
            "Por las entradas de efectivo por recaudos de clientes o aportes.",
            "Por las consignaciones diarias en cuentas bancarias o pagos menores.",
            "Recibir $500.000 en efectivo por una venta de contado."),
        CommonAccountInfo("110510", "Caja menor", PucNature.DEBITO,
            "Fondo fijo en efectivo destinado a sufragar gastos menores y urgentes.",
            "Por la creación o reembolso del fondo de caja menor.",
            "Por los pagos individuales realizados con el fondo de caja menor.",
            "Pagar $30.000 en efectivo por un servicio de mensajería urgente."),
        CommonAccountInfo("111005", "Bancos moneda nacional", PucNature.DEBITO,
            "Depósitos en cuentas corrientes en bancos del país.",
            "Por las consignaciones, transferencias recibidas y abonos de clientes.",
            "Por los pagos con transferencia, cheques girados y comisiones bancarias.",
            "Consignar $2.000.000 en la cuenta corriente bancaria."),
        CommonAccountInfo("130505", "Clientes nacionales", PucNature.DEBITO,
            "Facturas y cuentas por cobrar a compradores por ventas de bienes o servicios a crédito.",
            "Por el valor de las facturas de venta emitidas a crédito a los clientes.",
            "Por los pagos, abonos o devoluciones recibidos de los clientes.",
            "Vender mercancía a crédito por $3.000.000 a 30 días."),
        CommonAccountInfo("130515", "Clientes del exterior", PucNature.DEBITO,
            "Cuentas por cobrar en moneda extranjera a compradores internacionales.",
            "Por las exportaciones o ventas a crédito realizadas a clientes extranjeros.",
            "Por las divisas recibidas en pago de las exportaciones.",
            "Exportar servicios por USD $5,000 a un cliente en EE.UU."),
        CommonAccountInfo("133005", "Anticipos a proveedores", PucNature.DEBITO,
            "Dineros entregados a proveedores como adelanto para futuras compras de insumos.",
            "Por los desembolsos entregados al proveedor como anticipo.",
            "Por cruce o legalización del anticipo al recibir la factura de compra definitiva.",
            "Girar 50% de anticipo ($1.500.000) para compra de inventario."),
        CommonAccountInfo("135515", "Retención en la fuente", PucNature.DEBITO,
            "Anticipo del impuesto de renta practicado por los clientes al efectuar pagos.",
            "Por el valor de las retenciones en renta que nos practican los clientes al facturarles.",
            "Por la aplicación o cruce del saldo a favor al declarar renta ante la DIAN.",
            "Un cliente nos retiene $75.000 (2.5%) al pagar nuestra factura."),
        CommonAccountInfo("135518", "Impuesto a las ventas retenido (ReteIVA)", PucNature.DEBITO,
            "IVA retenido por clientes agentes de retención al comprar bienes o servicios.",
            "Por el valor del ReteIVA (15% del IVA) practicado por el cliente.",
            "Por el cruce contra el IVA por pagar al declarar ante la DIAN.",
            "Un gran contribuyente nos practica ReteIVA por $57.000."),
        CommonAccountInfo("136530", "Préstamos a trabajadores", PucNature.DEBITO,
            "Créditos y anticipos de dinero concedidos a los empleados de la empresa.",
            "Por los desembolsos de préstamos aprobados al personal.",
            "Por las deducciones mensuales efectuadas en la nómina del trabajador.",
            "Prestar $1.000.000 a un empleado para calamidad doméstica."),
        CommonAccountInfo("143505", "Mercancías no fabricadas por la empresa", PucNature.DEBITO,
            "Inventario de bienes adquiridos para la comercialización sin transformación.",
            "Por el costo de las compras de mercancías y devoluciones en compras.",
            "Por el costo de la mercancía vendida (despachos) y devoluciones a proveedores.",
            "Comprar $5.000.000 en mercancía para revender."),
        CommonAccountInfo("152405", "Muebles y enseres", PucNature.DEBITO,
            "Escritorios, sillas, archiveros y estanterías para uso administrativo.",
            "Por el costo de adquisición de los muebles de oficina.",
            "Por la baja o venta del activo fijo por obsolescencia o renovación.",
            "Comprar escritorios ejecutivos por $2.500.000."),
        CommonAccountInfo("152805", "Equipo de computación y comunicación", PucNature.DEBITO,
            "Computadores, portátiles, servidores y equipos de red de la empresa.",
            "Por el costo de compra de equipos informáticos y tecnológicos.",
            "Por la baja, descarte o venta de equipos obsoletos.",
            "Adquirir 3 laptops para el personal por $9.000.000."),
        CommonAccountInfo("154005", "Autos, camionetas y camperos", PucNature.DEBITO,
            "Vehículos automotores propiedad de la empresa para transporte o gerencia.",
            "Por la compra de vehículos automotores.",
            "Por la venta o baja contable del vehículo.",
            "Comprar una camioneta para reparto por $60.000.000."),
        CommonAccountInfo("159215", "Depreciación acumulada edificaciones", PucNature.CREDITO,
            "Desgaste técnico sistemático acumulado de los edificios de la empresa.",
            "Por la reversión de depreciación en caso de venta o baja del activo.",
            "Por el gasto mensual calculado por depreciación de las construcciones.",
            "Registrar la depreciación mensual de la bodega por $500.000."),
        CommonAccountInfo("159220", "Depreciación acumulada maquinaria", PucNature.CREDITO,
            "Desgaste acumulado de la maquinaria industrial de producción.",
            "Por la reversión en caso de retiro de la maquinaria.",
            "Por el cálculo mensual de depreciación de la maquinaria fabril.",
            "Registrar depreciación de tornos y prensas por $1.200.000."),
        CommonAccountInfo("210510", "Pagarés bancarios", PucNature.CREDITO,
            "Préstamos comerciales a corto plazo contraídos con instituciones financieras.",
            "Por los pagos o abonos a capital realizados al banco.",
            "Por el valor de los créditos desembolsados por el banco.",
            "Recibir desembolso de un pagaré bancario por $30.000.000."),
        CommonAccountInfo("220505", "Proveedores nacionales", PucNature.CREDITO,
            "Deudas comerciales por compra de mercancías e insumos a crédito en el país.",
            "Por los pagos o transferencias efectuadas a los proveedores.",
            "Por el valor de las facturas de compra recibidas a crédito.",
            "Comprar inventario a crédito a 60 días por $4.000.000."),
        CommonAccountInfo("233525", "Honorarios por pagar", PucNature.CREDITO,
            "Obligaciones por servicios profesionales independientes causados pendientes de giro.",
            "Por el pago realizado al profesional o asesor independiente.",
            "Por el valor de la cuenta de cobro o factura por honorarios causada.",
            "Causar honorarios del contador por $1.500.000."),
        CommonAccountInfo("233550", "Servicios públicos por pagar", PucNature.CREDITO,
            "Facturas de energía, acueducto, gas y telecomunicaciones causadas pendientes de cancelar.",
            "Por el pago de las facturas de servicios públicos.",
            "Por el valor de las facturas mensuales recibidas de servicios.",
            "Causar el recibo de energía de la oficina por $350.000."),
        CommonAccountInfo("233595", "Otros costos y gastos por pagar", PucNature.CREDITO,
            "Obligaciones corrientes diversas no clasificadas en cuentas anteriores.",
            "Por los pagos efectuados de estos conceptos.",
            "Por los gastos operacionales causados pendientes de pago.",
            "Causar vigilancia privada del mes por $2.200.000."),
        CommonAccountInfo("236515", "Retefuente honorarios", PucNature.CREDITO,
            "Retención en la fuente practicada sobre pagos por servicios profesionales (10% o 11%).",
            "Por el pago mensual de la retención acumulada a la DIAN.",
            "Por el valor retenido al pagar honorarios a personas naturales o jurídicas.",
            "Retener 10% ($150.000) al pagar honorarios al asesor jurídico."),
        CommonAccountInfo("236525", "Retefuente servicios", PucNature.CREDITO,
            "Retención en la fuente sobre contratos de servicios técnicos y generales (4% o 6%).",
            "Por la transferencia mensual de la retención a la DIAN.",
            "Por el impuesto retenido al pagar facturas de servicios a contratistas.",
            "Retener 4% ($80.000) al pagar mantenimiento técnico."),
        CommonAccountInfo("236530", "Retefuente arrendamientos", PucNature.CREDITO,
            "Retención en la fuente del 3.5% sobre cánones de arrendamiento de inmuebles.",
            "Por el pago del impuesto retenido a la DIAN.",
            "Por la retención practicada al pagar el arriendo mensual al propietario.",
            "Retener 3.5% ($70.000) al pagar el canon de arriendo."),
        CommonAccountInfo("236540", "Retefuente compras", PucNature.CREDITO,
            "Retención en la fuente del 2.5% practicada en compras generales de mercancías.",
            "Por la declaración y pago mensual de retenciones a la DIAN.",
            "Por la retención practicada al pagar facturas a proveedores.",
            "Retener 2.5% ($100.000) al pagar factura a un proveedor."),
        CommonAccountInfo("236701", "Impuesto a las ventas retenido (ReteIVA)", PucNature.CREDITO,
            "IVA retenido a proveedores que debe declararse y pagarse a la DIAN.",
            "Por el pago del ReteIVA liquidado en la declaración bimestral/cuatrimestral.",
            "Por el 15% del IVA retenido al efectuar pagos a proveedores régimen común.",
            "Retener $57.000 de ReteIVA en una compra gravada."),
        CommonAccountInfo("236805", "ReteICA por pagar", PucNature.CREDITO,
            "Impuesto de industria y comercio retenido a proveedores para pago al municipio.",
            "Por la consignación del impuesto retenido a la tesorería distrital o municipal.",
            "Por la retención de ICA practicada en pagos a proveedores locales.",
            "Retener ReteICA por $45.000 en un pago comercial."),
        CommonAccountInfo("237005", "Aportes a EPS por pagar", PucNature.CREDITO,
            "Deducciones de nómina y aportes patronales obligatorios al sistema de salud.",
            "Por el pago mensual de la PILA a las Entidades Promotoras de Salud.",
            "Por la causación de los aportes a salud de empleados y empresa.",
            "Causar el aporte a salud del mes por $850.000."),
        CommonAccountInfo("237006", "Aportes a fondos de pensiones", PucNature.CREDITO,
            "Aportes obligatorios descontados a trabajadores y asumidos por el empleador para pensiones.",
            "Por el pago de la PILA a los fondos privados de pensiones o Colpensiones.",
            "Por la causación de pensiones de la nómina mensual.",
            "Causar aportes a pensión del mes por $1.200.000."),
        CommonAccountInfo("237010", "Aportes parafiscales (SENA, ICBF, Cajas)", PucNature.CREDITO,
            "Obligaciones por aportes parafiscales destinados al SENA, ICBF y Cajas de Compensación.",
            "Por el pago mensual parafiscal a las entidades perceptoras.",
            "Por la causación de los parafiscales de nómina.",
            "Causar parafiscales del mes por $750.000."),
        CommonAccountInfo("240805", "IVA generado", PucNature.CREDITO,
            "Impuesto sobre las ventas facturado en operaciones de venta de bienes y servicios.",
            "Por las anulaciones de ventas o IVA en devoluciones de clientes.",
            "Por el IVA del 19% facturado en cada venta realizada.",
            "Facturar IVA del 19% por $950.000 en una venta."),
        CommonAccountInfo("240810", "IVA descontable", PucNature.DEBITO,
            "IVA pagado en la adquisición de bienes y servicios deducible del IVA generado.",
            "Por el valor del IVA pagado en compras de mercancías, insumos y gastos.",
            "Por el cruce o compensación contra el IVA generado al declarar ante la DIAN.",
            "Pagar $380.000 de IVA en la compra de inventario."),
        CommonAccountInfo("241205", "ICA por pagar", PucNature.CREDITO,
            "Impuesto de industria y comercio municipal consolidado adeudado.",
            "Por el pago del impuesto liquidado a la secretaría de hacienda municipal.",
            "Por la causación bimestral o anual del impuesto de ICA.",
            "Causar el impuesto de ICA del bimestre por $600.000."),
        CommonAccountInfo("250505", "Salarios por pagar", PucNature.CREDITO,
            "Remuneración neta adeudada a los trabajadores al finalizar el mes o quincena.",
            "Por el pago de la nómina realizado a las cuentas bancarias de los empleados.",
            "Por la causación de los sueldos devengados en la planilla de nómina.",
            "Causar la nómina neta quincenal por $10.000.000."),
        CommonAccountInfo("251005", "Cesantías consolidadas", PucNature.CREDITO,
            "Auxilio legal de cesantías acumulado a favor de cada trabajador (un mes por año).",
            "Por las consignaciones anuales al fondo de cesantías o retiros anticipados.",
            "Por la causación mensual o anual del auxilio de cesantías.",
            "Causar la provisión mensual de cesantías por $900.000."),
        CommonAccountInfo("251505", "Intereses sobre cesantías", PucNature.CREDITO,
            "Rendimientos legales del 12% anual sobre cesantías acumuladas pagaderos en enero.",
            "Por el pago directo de los intereses a los trabajadores en enero.",
            "Por la causación mensual de los intereses de cesantías.",
            "Causar intereses sobre cesantías del mes por $108.000."),
        CommonAccountInfo("252005", "Prima de servicios", PucNature.CREDITO,
            "Prestación social legal semestral acumulada para pago en junio y diciembre.",
            "Por el desembolso de la prima a los empleados en junio y diciembre.",
            "Por la causación mensual de la prima de servicios.",
            "Causar provisión de prima de servicios por $900.000."),
        CommonAccountInfo("252505", "Vacaciones consolidadas", PucNature.CREDITO,
            "Descanso remunerado acumulado adeudado a los trabajadores.",
            "Por el pago de vacaciones disfrutadas o compensadas en dinero.",
            "Por la causación mensual del derecho a vacaciones de los empleados.",
            "Causar provisión de vacaciones del mes por $375.000."),
        CommonAccountInfo("280505", "Anticipos de clientes", PucNature.CREDITO,
            "Dineros recibidos de compradores como adelanto para futuros despachos de mercancía.",
            "Por la legalización del anticipo al facturar y entregar la mercancía.",
            "Por el dinero recibido por adelantado de los clientes.",
            "Recibir un anticipo del 50% ($2.500.000) para un pedido futuro."),
        CommonAccountInfo("311505", "Aportes sociales", PucNature.CREDITO,
            "Aportes de capital entregados por los socios al constituir o capitalizar la sociedad.",
            "Por devoluciones de aportes o liquidación de socios.",
            "Por los valores iniciales o aumentos de capital aportados.",
            "Registrar el capital social inicial por $50.000.000."),
        CommonAccountInfo("360505", "Utilidad del ejercicio", PucNature.CREDITO,
            "Ganancia neta obtenida por la empresa al cierre del periodo contable.",
            "Por la distribución de dividendos o traslado a utilidades acumuladas.",
            "Por el traslado de los ingresos, costos y gastos netos al cierre del año.",
            "Registrar la utilidad neta del año por $25.000.000."),
        CommonAccountInfo("361005", "Pérdida del ejercicio", PucNature.DEBITO,
            "Déficit financiero obtenido en las operaciones del año contable.",
            "Por el traslado de la pérdida neta al cierre del ejercicio.",
            "Por el enjugamiento o absorción de pérdidas con reservas.",
            "Registrar la pérdida neta del ejercicio por $5.000.000."),
        CommonAccountInfo("413536", "Venta de productos terminados", PucNature.CREDITO,
            "Ingresos operacionales por la comercialización de productos manufacturados.",
            "Por devoluciones en ventas de productos terminados.",
            "Por las facturas emitidas por venta de productos fabricados.",
            "Vender productos terminados por $15.000.000."),
        CommonAccountInfo("417505", "Devoluciones en ventas", PucNature.DEBITO,
            "Mercancías devueltas por los clientes que disminuyen los ingresos brutos.",
            "Por el valor de la mercancía devuelta por los compradores.",
            "Por el cierre de la cuenta al final del periodo.",
            "Recibir devolución de mercancía defectuosa por $500.000."),
        CommonAccountInfo("421005", "Intereses financieros", PucNature.CREDITO,
            "Ingresos por rendimientos de depósitos bancarios, CDT o préstamos otorgados.",
            "Por ajustes o anulaciones de intereses.",
            "Por los intereses ganados abonados por los bancos o deudores.",
            "Recibir $150.000 por intereses de una cuenta de ahorros."),
        CommonAccountInfo("429553", "Aprovechamientos diversos", PucNature.CREDITO,
            "Ingresos no operacionales fortuitos por condonaciones, sobrantes o recuperaciones.",
            "Por ajustes contables.",
            "Por el valor de los aprovechamientos o ingresos ocasionales recibidos.",
            "Registrar un ingreso por condonación de una deuda menor por $200.000."),
        CommonAccountInfo("510506", "Sueldos administrativos", PucNature.DEBITO,
            "Remuneración básica del personal de gerencia, administración y oficina.",
            "Por el valor devengado por los empleados en la planilla de nómina.",
            "Por traslados o anulaciones de sueldos.",
            "Causar el sueldo básico de la gerente por $4.000.000."),
        CommonAccountInfo("510515", "Horas extras y recargos", PucNature.DEBITO,
            "Pagos adicionales por trabajo en horas suplementarias, nocturnas, dominicales o festivos.",
            "Por el valor de las horas extras liquidadas en la nómina.",
            "Por anulaciones.",
            "Pagar horas extras al personal de seguridad por $350.000."),
        CommonAccountInfo("510527", "Auxilio de transporte", PucNature.DEBITO,
            "Subsidio de transporte legal obligatorio pagado a los empleados que devengan hasta 2 SMLV.",
            "Por el auxilio de transporte liquidado en la nómina mensual.",
            "Por anulaciones.",
            "Pagar auxilio de transporte a los trabajadores por $800.000."),
        CommonAccountInfo("510530", "Cesantías", PucNature.DEBITO,
            "Gasto por la apropiación mensual del auxilio de cesantías del personal administrativo.",
            "Por la provisión mensual calculada del 8.33% sobre salarios.",
            "Por ajustes o reversiones.",
            "Registrar la provisión mensual de cesantías de administración por $450.000."),
        CommonAccountInfo("510533", "Intereses sobre cesantías", PucNature.DEBITO,
            "Gasto por la provisión mensual del 12% anual sobre las cesantías.",
            "Por el cálculo mensual de intereses de cesantías.",
            "Por ajustes.",
            "Registrar provisión de intereses de cesantías por $54.000."),
        CommonAccountInfo("510536", "Prima de servicios", PucNature.DEBITO,
            "Gasto por la apropiación mensual de la prima legal de servicios.",
            "Por la provisión mensual del 8.33% sobre salarios.",
            "Por ajustes.",
            "Registrar provisión de prima de administración por $450.000."),
        CommonAccountInfo("510539", "Vacaciones", PucNature.DEBITO,
            "Gasto por la apropiación mensual del descanso remunerado de los empleados.",
            "Por la provisión mensual calculada de vacaciones.",
            "Por ajustes.",
            "Registrar provisión de vacaciones por $185.000."),
        CommonAccountInfo("510568", "Aportes cajas de compensación", PucNature.DEBITO,
            "Aportes parafiscales del 4% asumidos por la empresa a Cajas de Compensación Familiar.",
            "Por el pago o causación del 4% parafiscal.",
            "Por ajustes.",
            "Causar el 4% de caja de compensación por $400.000."),
        CommonAccountInfo("510569", "Aportes ICBF y SENA", PucNature.DEBITO,
            "Aportes parafiscales al SENA (2%) y al ICBF (3%) cuando aplique.",
            "Por la causación de los aportes parafiscales al SENA e ICBF.",
            "Por ajustes.",
            "Causar aportes a SENA e ICBF por $500.000."),
        CommonAccountInfo("510570", "Aportes a EPS", PucNature.DEBITO,
            "Aportes patronales obligatorios a la seguridad social en salud (EPS).",
            "Por la causación del porcentaje de salud a cargo del empleador (8.5%).",
            "Por ajustes.",
            "Causar el aporte patronal a salud por $850.000."),
        CommonAccountInfo("510572", "Aportes a fondos de pensiones", PucNature.DEBITO,
            "Aportes patronales obligatorios a fondos de pensiones (12%).",
            "Por la causación del aporte a pensión a cargo del empleador.",
            "Por ajustes.",
            "Causar el aporte patronal a pensiones por $1.200.000."),
        CommonAccountInfo("511010", "Asesoría jurídica y legal", PucNature.DEBITO,
            "Honorarios pagados por servicios de abogados y consultoría legal corporativa.",
            "Por el valor de los honorarios jurídicos causados o pagados.",
            "Por anulaciones.",
            "Pagar $2.000.000 por asesoría en un contrato legal."),
        CommonAccountInfo("512010", "Arrendamientos de oficinas", PucNature.DEBITO,
            "Cánones de arrendamiento pagados por el uso de oficinas y locales administrativos.",
            "Por el valor del arriendo mensual de las instalaciones.",
            "Por anulaciones.",
            "Pagar el arriendo de la oficina principal por $3.500.000."),
        CommonAccountInfo("513525", "Energía eléctrica", PucNature.DEBITO,
            "Gasto por el consumo de energía y fluido eléctrico en oficinas y administración.",
            "Por el valor de la factura mensual de energía.",
            "Por anulaciones.",
            "Pagar la factura de energía por $450.000."),
        CommonAccountInfo("513535", "Teléfono y comunicaciones", PucNature.DEBITO,
            "Gasto por servicios de telefonía fija, móvil e internet de la administración.",
            "Por el valor de las facturas de telecomunicaciones.",
            "Por anulaciones.",
            "Pagar el plan de internet y telefonía por $280.000."),
        CommonAccountInfo("514510", "Mantenimiento de edificios", PucNature.DEBITO,
            "Reparaciones locativas, pintura y mantenimiento general de las oficinas.",
            "Por las facturas de reparaciones y arreglos locativos.",
            "Por anulaciones.",
            "Pagar pintura y arreglo de paredes por $1.200.000."),
        CommonAccountInfo("519525", "Elementos de aseo y cafetería", PucNature.DEBITO,
            "Insumos de limpieza, café, agua y suministros para la cafetería de la oficina.",
            "Por la compra de suministros de aseo y cafetería.",
            "Por anulaciones.",
            "Comprar café y suministros de aseo por $200.000."),
        CommonAccountInfo("519530", "Útiles, papelería y fotocopias", PucNature.DEBITO,
            "Papel, bolígrafos, impresiones y material de papelería para uso administrativo.",
            "Por la compra de útiles y papelería de oficina.",
            "Por anulaciones.",
            "Comprar resmas de papel y suministros de papelería por $180.000."),
        CommonAccountInfo("519535", "Libros, revistas y suscripciones", PucNature.DEBITO,
            "Suscripciones a normatividad, revistas especializadas y publicaciones técnicas.",
            "Por el pago de suscripciones y material bibliográfico.",
            "Por anulaciones.",
            "Pagar suscripción anual a portal tributario por $1.200.000."),
        CommonAccountInfo("523560", "Fletes y acarreos en ventas", PucNature.DEBITO,
            "Gastos de transporte y envíos de mercancías despachadas a los clientes.",
            "Por el pago de servicios de transporte por entregas comerciales.",
            "Por anulaciones.",
            "Pagar flete a empresa transportadora por $320.000."),
        CommonAccountInfo("530515", "Comisiones bancarias", PucNature.DEBITO,
            "Cargos y tarifas cobrados por bancos por transferencias, manejo de cuenta y chequeras.",
            "Por el valor de las notas débito bancarias por comisiones.",
            "Por anulaciones.",
            "Pagar comisión bancaria por transferencia internacional por $85.000."),
        CommonAccountInfo("530535", "Descuentos comerciales condicionados", PucNature.DEBITO,
            "Descuentos otorgados a clientes por pronto pago de sus facturas.",
            "Por el valor del descuento concedido al cliente por pago anticipado.",
            "Por anulaciones.",
            "Conceder descuento del 5% ($100.000) por pago antes de 10 días."),
        CommonAccountInfo("530595", "Gastos bancarios diversos", PucNature.DEBITO,
            "Erogaciones financieras menores como chequeras, certificaciones o GMF (4x1000).",
            "Por el valor cobrado por el banco por gravamen a los movimientos financieros.",
            "Por anulaciones.",
            "Causar el cobro del 4x1000 en transacciones bancarias por $120.000."),
        CommonAccountInfo("613536", "Costo de ventas productos terminados", PucNature.DEBITO,
            "Costo de adquisición o fabricación de los productos terminados vendidos.",
            "Por el valor en libros del inventario entregado al despachar al cliente.",
            "Por devoluciones en compras o ajustes de inventario.",
            "Registrar el costo de los productos vendidos por $8.000.000.")
    )
}
