package com.example.model

/**
 * Provides 1-2 line plain-language micro-guides for Colombian PUC accounts,
 * explaining in simple words what the account represents and how it moves.
 */
object PucExplanationHelper {

    fun getMicroGuide(code: String, name: String, nature: PucNature): String {
        return when (code) {
            // Clases (1 dígito)
            "1" -> "Representa todos los bienes, dinero y derechos que posee la empresa. Aumenta con compras, cobros y recaudos; disminuye con pagos y ventas."
            "2" -> "Agrupa todas las deudas y obligaciones contraídas con bancos, proveedores, empleados y el Estado. Aumenta al endeudarse, disminuye al pagar."
            "3" -> "El patrimonio neto de los dueños o accionistas: capital aportado, reservas acumuladas y utilidades del ejercicio."
            "4" -> "Los ingresos ordinarios y extraordinarios generados por la venta de bienes o prestación de servicios del negocio."
            "5" -> "Los gastos operacionales de administración y ventas necesarios para el funcionamiento diario de la empresa."
            "6" -> "El costo de adquisición o fabricación de las mercancías y bienes vendidos a los clientes."
            "7" -> "Los costos directos e indirectos incurridos en los procesos de producción o manufactura."
            "8" -> "Cuentas de orden deudoras: derechos contingentes o compromisos que no afectan directamente el balance general."
            "9" -> "Cuentas de orden acreedoras: responsabilidades contingentes o bienes recibidos de terceros en custodia."

            // Grupos Activo (2 dígitos)
            "11" -> "Disponible: Dinero en efectivo, depósitos bancarios y equivalentes de liquidez inmediata."
            "12" -> "Inversiones: Acciones, bonos, CDT y títulos valores adquiridos para rentabilidad o control."
            "13" -> "Deudores: Cuentas por cobrar a clientes, anticipos de impuestos, empleados y socios."
            "14" -> "Inventarios: Mercancías, materias primas y productos en proceso listos para comercializar."
            "15" -> "Propiedades, Planta y Equipo: Bienes duraderos tangibles usados en la operación (terrenos, equipos, vehículos)."
            "16" -> "Intangibles: Bienes no físicos con valor económico comercial (marcas, patentes, software, franquicias)."
            "17" -> "Diferidos: Gastos pagados por anticipado pendientes de amortizar (seguros, intereses, arriendos)."
            "18" -> "Otros Activos: Bienes de arte, cultura, depósitos dados en garantía y activos diversos."
            "19" -> "Valorizaciones: Incrementos en el valor comercial de inversiones o propiedades frente a su costo en libros."

            // Grupos Pasivo (2 dígitos)
            "21" -> "Obligaciones Financieras: Pagarés, préstamos y sobregiros con bancos e instituciones de crédito."
            "22" -> "Proveedores: Facturas y cuentas por pagar a los suministradores de materias primas e insumos."
            "23" -> "Cuentas por Pagar: Costos, gastos, retenciones en la fuente y acreedores comerciales varios."
            "24" -> "Impuestos, Gravámenes y Tasas: Deudas fiscales por IVA, impuesto de renta, industria y comercio."
            "25" -> "Obligaciones Laborales: Salarios, cesantías, primas y vacaciones adeudadas a los trabajadores."
            "26" -> "Pasivos Estimados y Provisiones: Reservas para contingencias, litigios, garantías y demandas."
            "27" -> "Diferidos: Ingresos recibidos por anticipado pendientes de causar en futuros periodos."
            "28" -> "Otros Pasivos: Anticipos de clientes, depósitos recibidos y fondos de terceros."
            "29" -> "Bonos y Pagarés Emitidos: Títulos de deuda corporativa colocados en el mercado de capitales."

            // Grupos Patrimonio (2 dígitos)
            "31" -> "Capital Social: Aportes iniciales y suscritos por los socios o accionistas de la empresa."
            "32" -> "Superávit de Capital: Primas en colocación de acciones, donaciones y capital adicional."
            "33" -> "Reservas: Utilidades retenidas por mandato legal, estatutario o decisiones de la asamblea."
            "34" -> "Revalorización del Patrimonio: Ajustes por inflación acumulados del patrimonio histórico."
            "35" -> "Dividendos o Participaciones Decretados en Acciones: Acciones propias reemitidas."
            "36" -> "Resultados del Ejercicio: Utilidad o pérdida neta obtenida en el periodo contable actual."
            "37" -> "Resultados de Ejercicios Anteriores: Utilidades acumuladas o pérdidas de años pasados por distribuir."
            "38" -> "Superávit por Valorizaciones: Valorizaciones netas de inversiones y activos fijos."

            // Grupos Ingresos (2 dígitos)
            "41" -> "Operacionales: Ingresos principales por ventas y prestación de servicios del objeto social."
            "42" -> "No Operacionales: Ingresos secundarios por intereses, arriendos, comisiones o venta de activos."

            // Grupos Gastos (2 dígitos)
            "51" -> "Operacionales de Administración: Gastos de personal gerencial, papelería, servicios y arriendos de oficina."
            "52" -> "Operacionales de Ventas: Gastos directos de comercialización, publicidad, comisiones y fletes."
            "53" -> "No Operacionales: Gastos financieros, comisiones bancarias, intereses y pérdidas en baja de activos."
            "54" -> "Impuesto de Renta y Complementarios: Provisión del impuesto sobre la renta del ejercicio."
            "59" -> "Ganancias y Pérdidas: Cuenta transitoria para el cierre de ingresos, costos y gastos al final del año."

            // Grupos Costos (2 dígitos)
            "61" -> "Costo de Ventas: Valor de adquisición o producción de los bienes y servicios vendidos."
            "62" -> "Compras: Adquisiciones de materias primas, repuestos o mercancías para la venta."
            "71" -> "Materia Prima: Costo de insumos directos utilizados en la fabricación de productos."
            "72" -> "Mano de Obra Directa: Salarios y prestaciones del personal de planta en producción."
            "73" -> "Costos Indirectos: Insumos, energía, depreciaciones y servicios de la planta fabril."
            "74" -> "Contratos de Servicios: Servicios externos de fabricación o maquila."

            // Cuentas principales auditadas (4 dígitos)
            "1105" -> "Caja: Dinero en efectivo y cheques físicos en poder de la empresa. Sube al recibir recaudos, baja al consignar en bancos."
            "1110" -> "Bancos: Depósitos en cuentas corrientes bancarias para manejo de giros, transferencias y pagos."
            "1115" -> "Remesas en tránsito: Dinero o cheques enviados a sucursales o bancos pendientes de confirmación y abono."
            "1120" -> "Cuentas de ahorro: Fondos a la vista en entidades financieras que generan rendimientos periódicos."
            "1125" -> "Fondos: Dinero destinado a fondos fijos operativos o encargos fiduciarios de liquidez."
            "1205" -> "Acciones: Títulos valores representativos de capital social en sociedades anónimas o limitadas."
            "1210" -> "Cuotas o partes de interés social: Aportes en sociedades de personas (limitadas, colectivas)."
            "1215" -> "Bonos: Títulos de deuda corporativa o gubernamental adquiridos como inversión financiera."
            "1220" -> "Cédulas: Cédulas hipotecarias u otros títulos de crédito con garantía real."
            "1225" -> "Certificados: CDT y certificados de depósito a término emitidos por bancos."
            "1230" -> "Papeles comerciales: Pagarés corporativos de corto plazo emitidos por empresas del sector real."
            "1235" -> "Títulos: Títulos de tesorería (TES) o de deuda pública negociables."
            "1245" -> "Derechos fiduciarios: Participaciones en patrimonios autónomos o fideicomisos de inversión."
            "1295" -> "Otras inversiones: Inversiones financieras diversas no clasificadas en cuentas anteriores."
            "1299" -> "Provisiones inversiones: Estimación para cubrir posibles pérdidas en el valor de las inversiones."
            "1305" -> "Clientes: Facturas y cuentas comerciales por cobrar a compradores por venta de bienes y servicios."
            "1310" -> "Cuentas corrientes comerciales: Saldos exigibles a clientes por operaciones mercantiles recurrentes."
            "1315" -> "Cuentas por cobrar a casa matriz: Valores adeudados por la oficina principal en el exterior o interior."
            "1320" -> "Cuentas por cobrar a vinculados económicos: Saldos con sucursales, subsidiarias o asociadas."
            "1325" -> "Cuentas por cobrar a socios y accionistas: Préstamos o valores pendientes de pago por aportes."
            "1330" -> "Anticipos y avances: dineros entregados a proveedores o contratistas a cuenta de futuras compras."
            "1340" -> "Promesas de compraventa: Valores entregados como arras o pago parcial por adquisición de bienes raíces."
            "1345" -> "Ingresos por cobrar: Intereses, dividendos, arriendos o comisiones causadas pendientes de recaudo."
            "1355" -> "Anticipo de impuestos y contribuciones: Retenciones en la fuente a favor de la empresa y saldos a favor."
            "1360" -> "Reclamaciones: Valores por cobrar a compañías aseguradoras por siniestros o a terceros por litigios."
            "1365" -> "Cuentas por cobrar a trabajadores: Préstamos, anticipos de nómina y deudas del personal."
            "1380" -> "Deudores diversos: Cuentas por cobrar a terceros por conceptos diferentes a la operación principal."
            "1399" -> "Provisiones deudores: Estimación conservadora para cubrir deudas de difícil cobro (cartera morosa)."
            "1405" -> "Materias primas: Materiales principales que serán transformados en el proceso productivo."
            "1410" -> "Productos en proceso: Artículos parcialmente elaborados en la planta de manufactura."
            "1415" -> "Obras de construcción en curso: Costos acumulados en proyectos inmobiliarios o de infraestructura."
            "1425" -> "Productos terminados: Bienes fabricados listos para ser entregados a los compradores."
            "1430" -> "Subproductos, desperdicios y residuos: Materiales secundarios recuperados del proceso industrial."
            "1435" -> "Mercancías no fabricadas por la empresa: Inventarios adquiridos para revender sin transformación."
            "1450" -> "Terrenos: Predios adquiridos con el propósito específico de ser comercializados."
            "1455" -> "Materiales, repuestos y accesorios: Insumos de mantenimiento, repuestos y papelería almacenados."
            "1460" -> "Envases y empaques: Elementos de empaque destinados a la presentación y venta de productos."
            "1499" -> "Provisiones inventarios: Estimación por desvalorización, obsolescencia o pérdida de mercancías."
            "1504" -> "Terrenos: Predios urbanos o rurales de propiedad de la empresa donde opera u oficinas."
            "1508" -> "Construcciones y edificaciones: Inmuebles, bodegas, oficinas y locales comerciales propios."
            "1512" -> "Maquinaria y equipo: Aparatos y máquinas industriales empleados en la producción fabril."
            "1516" -> "Equipo de oficina: Muebles, escritorios, archivos y enseres administrativos."
            "1520" -> "Equipo de computación y comunicación: Servidores, equipos informáticos, redes y telefonía."
            "1524" -> "Equipo médico-científico: Aparatos de laboratorios, medicina o investigación técnica."
            "1528" -> "Flota y equipo de transporte: Automóviles, camiones, montacargas y vehículos de reparto."
            "1592" -> "Depreciación acumulada: Desgaste técnico sistemático de los activos fijos tangibles."
            "1599" -> "Provisiones propiedades, planta y equipo: Pérdida esperada en el valor comercial de los activos fijos."
            "1605" -> "Crédito mercantil (Goodwill): Valor adicional pagado sobre en negociaciones comerciales."
            "1610" -> "Marcas: Derechos exclusivos de propiedad industrial sobre nombres y logotipos comerciales."
            "1615" -> "Patentes: Privilegios de explotación sobre invenciones y desarrollos tecnológicos."
            "1620" -> "Concesiones y franquicias: Derechos otorgados por el Estado o marcas para operar negocios."
            "1625" -> "Know how: Conocimientos técnicos y fórmulas comerciales de propiedad de la empresa."
            "1705" -> "Gastos pagados por anticipado: Pólizas de seguro, intereses o arriendos cubiertos por adelantado."
            "1710" -> "Cargos diferidos: Erogaciones por organización, remodelaciones o mejoras pendientes de amortizar."
            "2105" -> "Bancos nacionales: Pagarés y créditos corrientes contraídos con instituciones financieras del país."
            "2110" -> "Bancos del exterior: Préstamos en moneda extranjera otorgados por bancos internacionales."
            "2115" -> "Corporaciones financieras: Obligaciones crediticias con corporaciones de desarrollo industrial."
            "2120" -> "Compañías de financiamiento: Deudas comerciales contraídas con financieras especializadas."
            "2205" -> "Proveedores nacionales: Facturas comerciales por pagar a suministradores locales de bienes."
            "2210" -> "Proveedores del exterior: Obligaciones en moneda extranjera con suministradores internacionales."
            "2305" -> "Cuentas por pagar a casa matriz: Deudas corrientes con la oficina principal extranjera o nacional."
            "2310" -> "Cuentas por pagar a vinculados económicos: Saldos comerciales con filiales o subsidiarias."
            "2315" -> "Cuentas por pagar a socios y accionistas: Préstamos u obligaciones monetarias con los dueños."
            "2320" -> "Cuentas por pagar a administradores: Anticipos o gastos reembolsables a directivos y gerentes."
            "2335" -> "Costos y gastos por pagar: Obligaciones por servicios, honorarios, arriendos y servicios públicos."
            "2340" -> "Instalaciones y servicios públicos: Facturas de energía, acueducto y gas causadas pendientes de pago."
            "2360" -> "Dividendos o participaciones por pagar: Utilidades aprobadas pendientes de entregar a los socios."
            "2365" -> "Retención en la fuente: Impuesto retenido a terceros en compras, honorarios y servicios por pagar a la DIAN."
            "2368" -> "Impuesto de industria y comercio retenido (ReteICA): Retención municipal por pagar al distrito."
            "2370" -> "Retenciones y aportes de nómina: Deducciones de salarios para EPS, pensiones y fondos de solidaridad."
            "2380" -> "Acreedores diversos: Deudas corrientes con terceros por conceptos distintos a la operación principal."
            "2404" -> "De renta y complementarios: Provisión por pagar del impuesto sobre la renta anual."
            "2408" -> "Impuesto sobre las ventas por pagar (IVA): IVA facturado a clientes menos IVA descontable en compras."
            "2412" -> "De industria y comercio (ICA): Impuesto municipal consolidado pendiente de declarar y pagar."
            "2505" -> "Salarios por pagar: Remuneración devengada por los trabajadores al cierre de cada periodo."
            "2510" -> "Cesantías consolidadas: Auxilio legal de cesantías acumulado a favor del personal."
            "2515" -> "Intereses sobre cesantías: Rendimientos legales del 12% anual sobre cesantías pagaderos en enero."
            "2520" -> "Prima de servicios: Prestación social semestral obligatoria adeudada a los trabajadores."
            "2525" -> "Vacaciones consolidadas: Descanso remunerado acumulado pendiente de disfrutar o pagar."
            "2540" -> "Indemnizaciones laborales: Compensaciones económicas por despidos sin justa causa u otros."
            "3105" -> "Capital suscrito y pagado: Aportes patrimoniales de los socios fundadores o ampliaciones sociales."
            "3305" -> "Reserva legal: Apropiación obligatoria del 10% de las utilidades líquidas para blindar el capital."
            "3310" -> "Reservas estatutarias: Fondos de capitalización ordenados por los estatutos de la sociedad."
            "3315" -> "Reservas facultativas: Apropiaciones voluntarias decididas por la asamblea general de accionistas."
            "3605" -> "Utilidad del ejercicio: Ganancia neta obtenida en el periodo contable actual."
            "3610" -> "Pérdida del ejercicio: Deficit financiero obtenido en las operaciones del año contable."
            "3705" -> "Utilidades acumuladas: Ganancias de ejercicios anteriores retenidas o pendientes de distribución."
            "3710" -> "Pérdidas acumuladas: Déficits financieros arrastrados de vigencias anteriores."
            "4105" -> "Agricultura, ganadería, silvicultura y pesca: Ingresos operacionales del sector primario."
            "4110" -> "Explotación de minas y canteras: Ventas y extracción de minerales e hidrocarburos."
            "4120" -> "Suministro de electricidad, gas y agua: Ingresos por servicios públicos domiciliarios."
            "4140" -> "Hoteles y restaurantes: Ingresos por servicios de hospedaje y alimentación comercial."
            "4150" -> "Actividad financiera: Ingresos operacionales de entidades bancarias y de crédito."
            "4155" -> "Actividades inmobiliarias: Arrendamientos y corretaje de bienes raíces propios o contratados."
            "4170" -> "Otras actividades de servicios: Ingresos por servicios diversos prestados a la comunidad."
            "4210" -> "Financieros: Ingresos por rendimientos de depósitos, intereses de préstamos y descuentos."
            "4215" -> "Dividendos y participaciones: Utilidades recibidas por inversiones en otras sociedades."
            "4220" -> "Arrendamientos: Ingresos ocasionales por alquiler de bienes muebles o inmuebles."
            "4225" -> "Comisiones: Honorarios o intermediaciones mercantiles ocasionales."
            "4230" -> "Honorarios: Retribuciones por servicios profesionales especializados ocasionales."
            "4245" -> "Utilidad en venta de activos: Ganancia obtenida al enajenar propiedades, planta o equipo."
            "5105" -> "Gastos de personal administrativo: Sueldos, auxilio de transporte, cesantías y aportes de oficina."
            "5110" -> "Honorarios: Pagos por asesorías legales, contables, financieras o técnicas."
            "5115" -> "Impuestos: Gravámenes fiscales directos asumidos por la empresa (predial, vehículos, timbre)."
            "5120" -> "Arrendamientos: Cánones pagados por el uso de oficinas, locales y bodegas administrativas."
            "5130" -> "Seguros: Primas de pólizas contratadas para protección de activos y personal."
            "5135" -> "Servicios: Gastos por energía, acueducto, teléfono, internet y aseo de instalaciones."
            "5140" -> "Gastos legales: Notarías, registros mercantiles, cámaras de comercio y trámites jurídicos."
            "5145" -> "Mantenimiento y reparaciones: Reparaciones locativas y técnicas de oficinas y equipos."
            "5160" -> "Depreciaciones: Gasto periódico por el desgaste operativo de los activos fijos de administración."
            "5205" -> "Gastos de personal de ventas: Sueldos, comisiones y prestaciones del equipo comercial."
            "5220" -> "Arrendamientos de ventas: Alquileres de puntos de venta, vitrinas y almacenes."
            "5235" -> "Servicios de ventas: Servicios públicos y comunicaciones de los puntos de comercialización."
            "5270" -> "Publicidad y propaganda: Campañas de mercadeo, avisos, pauta digital y difusión comercial."
            "5305" -> "Financieros: Intereses bancarios, comisiones, gravamen a los movimientos financieros (GMF)."
            "6135" -> "Comercio al por mayor y al por menor: Costo de adquisición de las mercancías vendidas."

            // Subcuentas específicas auditadas (ej. 110505, 110510, 110515, 112005, 112010, 112015)
            "110505" -> "Caja general: Efectivo y cheques disponibles en la caja principal de la empresa."
            "110510" -> "Caja menor: Fondo fijo en efectivo para pagos menores y urgentes de oficina."
            "110515" -> "Moneda extranjera: Efectivo en divisas (dólares, euros, etc.) valoradas a la tasa oficial."
            "111005" -> "Moneda nacional: Depósitos en cuentas corrientes en bancos del país."
            "111010" -> "Moneda extranjera: Cuentas corrientes bancarias denominadas en divisas extranjeras."
            "112005" -> "Bancos: Depósitos de ahorro en bancos comerciales del sistema financiero."
            "112010" -> "Corporaciones de ahorro y vivienda: Depósitos en entidades especializadas de fomento de construcción."
            "112015" -> "Organismos cooperativos financieros: Depósitos de ahorro en cooperativas financieras autorizadas."
            "130505" -> "Nacionales: Cuentas comerciales por cobrar a compradores y clientes del país."
            "130510" -> "Del exterior: Facturas comerciales por cobrar a clientes internacionales."
            "135515" -> "Retención en la fuente: Anticipo del impuesto sobre la renta practicado por clientes."
            "135518" -> "Impuesto a las ventas retenido (ReteIVA): IVA retenido por clientes agentes de retención."
            "143501" -> "Mercancías no fabricadas por la empresa: Inventario disponible para la comercialización."
            "220505" -> "Nacionales: Deudas comerciales con proveedores locales de bienes y servicios."
            "233525" -> "Honorarios: Servicios profesionales independientes causados pendientes de giro."
            "233540" -> "Arrendamientos: Cánones de arrendamiento causados pendientes de pago."
            "233550" -> "Servicios públicos: Facturas de energía, agua y comunicaciones pendientes de cancelación."
            "236515" -> "Honorarios: Retención en la fuente practicada sobre pagos por servicios profesionales (10% o 11%)."
            "236525" -> "Servicios: Retención en la fuente practicada sobre contratos de servicios técnicos y generales."
            "236540" -> "Compras: Retención en la fuente practicada sobre compras de bienes e insumos (2.5%)."
            "240801" -> "IVA generado: Impuesto sobre las ventas facturado en operaciones de venta."
            "240802" -> "IVA descontable: Impuesto sobre las ventas pagado en adquisiciones de bienes y servicios."
            "250505" -> "Salarios por pagar: Remuneración neta adeudada al personal al final del periodo."
            "251005" -> "Cesantías consolidadas: Auxilio legal de cesantías acumulado a favor del trabajador."
            "251505" -> "Intereses sobre cesantías: Rendimientos legales anuales sobre cesantías por pagar en enero."
            "252005" -> "Prima de servicios: Prestación social legal semestral acumulada para junio y diciembre."
            "252505" -> "Vacaciones consolidadas: Descanso remunerado acumulado pendiente de disfrutar."
            "310505" -> "Capital autorizado: Monto máximo de capital fijado por los estatutos sociales."
            "310510" -> "Capital suscrito: Parte del capital autorizado que los socios se comprometen a aportar."
            "310515" -> "Capital pagado: Valor efectivo de los aportes entregados por los socios a la sociedad."
            "413501" -> "Venta de mercancías: Ingresos operacionales por comercialización de productos al por mayor y detal."
            "510506" -> "Sueldos: Remuneración básica mensual del personal administrativo y gerencial."
            "510527" -> "Auxilio de transporte: Subsidio de transporte legal pagado a los empleados que aplican."
            "510530" -> "Cesantías: Gasto por apropiación mensual del auxilio de cesantías del personal."
            "513525" -> "Energía eléctrica: Gasto por consumo de luz y fluido eléctrico en oficinas."
            "513535" -> "Teléfono y comunicaciones: Gasto por servicios de telefonía fija, móvil e internet."
            "530520" -> "Intereses: Gasto financiero por intereses pagados sobre obligaciones bancarias."
            "613501" -> "Costo de mercancías vendidas: Valor en libros del inventario entregado en ventas comerciales."

            else -> {
                // Inteligente según el prefijo, nombre y naturaleza contable
                val cleanName = name.replaceFirstChar { it.uppercase() }
                when {
                    code.startsWith("11") -> "Disponible ($cleanName): Recursos monetarios de inmediata disponibilidad en efectivo o instituciones financieras."
                    code.startsWith("12") -> "Inversión ($cleanName): Títulos valores, acciones o depósitos rentables adquiridos por la entidad."
                    code.startsWith("13") -> "Deudor ($cleanName): Derecho exigible de cobro por transacciones comerciales o anticipos fiscales."
                    code.startsWith("14") -> "Inventario ($cleanName): Existencias materiales destinadas a la producción, transformación o venta."
                    code.startsWith("15") -> "Activo Fijo ($cleanName): Bien tangible duradero de propiedad de la empresa para su operación."
                    code.startsWith("16") -> "Intangible ($cleanName): Derecho comercial, marca o beneficio económico no físico."
                    code.startsWith("17") -> "Diferido activo ($cleanName): Gasto pagado por anticipado pendiente de causar."
                    code.startsWith("18") || code.startsWith("19") -> "Activo diverso ($cleanName): Bienes especiales o valorizaciones patrimoniales."
                    code.startsWith("21") -> "Obligación financiera ($cleanName): Deuda formal con entidades de crédito y financiamiento."
                    code.startsWith("22") -> "Proveedor ($cleanName): Cuenta comercial por pagar a suministradores de bienes y servicios."
                    code.startsWith("23") -> "Cuenta por pagar ($cleanName): Obligación corriente con acreedores varios o por retenciones."
                    code.startsWith("24") -> "Impuesto por pagar ($cleanName): Gravamen fiscal exigible por la administración tributaria."
                    code.startsWith("25") -> "Obligación laboral ($cleanName): Prestación, salario o beneficio adeudado al trabajador."
                    code.startsWith("26") || code.startsWith("27") -> "Pasivo estimado o diferido ($cleanName): Provisión por contingencia o ingreso anticipado."
                    code.startsWith("28") || code.startsWith("29") -> "Pasivo diverso ($cleanName): Fondos de terceros, depósitos o emisión de bonos."
                    code.startsWith("3") -> "Patrimonio ($cleanName): Participación residual neta de los propietarios en los activos de la entidad."
                    code.startsWith("4") -> "Ingreso ($cleanName): Incremento en los beneficios económicos operacionales o no operacionales."
                    code.startsWith("5") -> "Gasto ($cleanName): Erogación operacional administrativa o de ventas del periodo."
                    code.startsWith("6") -> "Costo de ventas ($cleanName): Erogación vinculada directamente a la adquisición o producción vendida."
                    code.startsWith("7") -> "Costo de producción ($cleanName): Insumo o labor aplicada al proceso manufacturero."
                    code.startsWith("8") || code.startsWith("9") -> "Cuenta de orden ($cleanName): Registro de control interno para contingencias o responsabilidades."
                    nature == PucNature.DEBITO -> "Cuenta ($cleanName): De naturaleza Débito, incrementa su saldo por el Debe y disminuye por el Haber."
                    else -> "Cuenta ($cleanName): De naturaleza Crédito, incrementa su saldo por el Haber y disminuye por el Debe."
                }
            }
        }
    }
}
